### ISSUE TITLE
Cli should not report OK for an invalid option for the given primary command

### ISSUE THREAD

**Issue by mcm001** [AerospaceNU/stm32-avionics#100]
In GitLab by @SamHaggans on Mar 29, 2023, 12:33

Currently, any CLI command sent with an invalid flag (e.x. `--config -f 1`) will report a positive acknowledgement back to the user (unless it fails for a different reason), even if that flag is not accepted for that command. The CLI does correctly ignore that flag (doesn't use it) but it should reject the command entirely if given an invalid flag, as otherwise the resulting command might not be doing what the user intended.

**Comment by SamHaggans** [comment]
Closed by #275
