### ISSUE TITLE
Scheduler/state machine refactor and abstraction

### ISSUE THREAD

**Issue by mcm001** [AerospaceNU/stm32-avionics#38]
In GitLab by @matthew.morley.ca on Nov 23, 2021, 10:29

> Creating a separate scheduler & state machine is something I have lined up for supporting angry geese & FCB in same project. I can discuss further with you at some point soon.

All our boards will have (generally) the same states and state transitions (Have we launched? are we falling? Are we low enough?) -- it would be great to abstract this away from the hardware so we can reuse a known-good state machine across multiple boards.

**Comment by SamHaggans** [comment]
Think this has mostly been done.
