### ISSUE TITLE
Utilize and Log Hardware Status

### ISSUE THREAD

**Issue by mcm001** [AerospaceNU/stm32-avionics#69]
In GitLab by @bf2799 on Jul 14, 2022, 09:08

Hardware status isn't logged anywhere, but this can be logged in the metadata so we know when offloading whether to take/ignore the data for particular hardware.

Also, hardware status isn't used everywhere sensor values are required on-board for further processing. If data is just logged/sent over radio, we don't need to check the hardware status, but if it's used for something like filtering to get altitude, the status should be checked as a fail-safe

**Comment by SamHaggans** [comment]
Superseded by #267
