### ISSUE TITLE
GPS Ground Elevation Reference

### ISSUE THREAD

**Issue by mcm001** [AerospaceNU/stm32-avionics#74]
In GitLab by @bf2799 on Sep 15, 2022, 11:26

Replace CLI ground elevation with an averaged GPS-given elevation. GPS elevation should be fairly good, though it might be 20-ish meters off. The longer it sits on the pad, however, the better the fix will get.

The CLI config should be overwritten with this value if it seems reasonable. Also, remember to add ground elevation reference to metadata, state log recovery, and metadata offload (in python) as part of this.

**Comment by SamHaggans** [comment]
Not sure if this is something we actually want to do - mixing AGL/MSL scares me. @mcm001 thoughts?
