### ISSUE TITLE
filter_addGravityRef only checks if accel > 0.5, no upper bound

### ISSUE THREAD

**Issue by mcm001** [AerospaceNU/stm32-avionics#94]
In GitLab by @matthew.morley.ca on Feb 28, 2023, 16:23

`if (fabs(accelSum) < 0.5 * G_ACCEL_EARTH * gravCount) return;`

This can evaluate to true right at liftoff too technically. Not a huge issue but probably worth adding an upper bound

**Comment by SamHaggans** [comment]
Was closed by 5534dcff448676241567a5f2a3fd8eea5f6897ea
